#!/bin/bash
# ~/.xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

eval $(ssh-agent)
start-pulseaudio-x11
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_ASKPASS=ssh-askpass
export SSH_AUTH_SOCK
# exec startxfce4
exec i3
