source ~/antigen/antigen.zsh

antigen bundle robbyrussell/oh-my-zsh lib/
antigen bundle jump

antigen bundle zsh-users/zsh-syntax-highlighting
# autosuggestions based on the history
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle git
antigen bundle gitignore
antigen bundle tmux
antigen bundle tmuxinator
# cargo autocomplete
antigen bundle cargo
# magnet link to torrent file with magnet_to_torrent
antigen bundle torrent

antigen bundle rand-quote

antigen bundle https://github.com/bobthecow/git-flow-completion

antigen theme https://github.com/halfo/lambda-mod-zsh-theme lambda-mod
# antigen theme robbyrussell
# antigen theme https://github.com/agnoster/agnoster-zsh-theme.git agnoster
# antigen theme candy

antigen apply

export PATH=~/bin:~/.gem/ruby/2.5.0/bin:$PATH

source $HOME/.cargo/env
[ -f $(which sccache) ] && export RUSTC_WRAPPER=sccache

# fix font rendering in Java
export JAVA_OPTS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"

export EDITOR=/usr/bin/vim
# map vi to vim
alias vi=$EDITOR

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# print execution time if > 10 seconds
export REPORTTIME=10

# better shell colors
BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-default-dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# alias to upload a file to sprunge.us
alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"

# sudo with aliases
# If the last character of the alias value is a space or tab character, then the next command word following the alias is also checked for alias expansion.
alias sudo='sudo '

# get tmux to work with true color
# alias tmux='TERM=xterm-256color tmux'
alias tmux='tmux -2'
alias mux='tmuxinator start'

alias prm=". $HOME/tools/prm/prm.sh"

# multiple tabs in termite
source /etc/profile.d/vte.sh

# load nix
. /home/me/.nix-profile/etc/profile.d/nix.sh

. ~/.drone/drone.vbrandl.net

# copied from http://www.tuxarena.com/2012/04/tutorial-colored-man-pages-how-it-works/
# maybe improve later
export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan

unsetopt autopushd

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"
export PATH="$HOME/.gem/ruby/2.5.0/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

# Linuxbrew
# export PATH="/home/me/.linuxbrew/bin:$PATH"
# export MANPATH="/home/me/.linuxbrew/share/man:$MANPATH"
# export INFOPATH="/home/me/.linuxbrew/share/info:$INFOPATH"
fpath=(~/.zsh/completions $fpath)

# added by travis gem
[ -f /home/me/.travis/travis.sh ] && source /home/me/.travis/travis.sh
export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"
export PATH="/home/me/.guix-profile/bin${PATH:+:}$PATH"
TIMEFMT=$'\nreal\t%*E\nuser\t%*U\nsys\t%*S\nmaxmem\t%M MB\nfaults\t%F'
#  vim: set filetype=zsh ts=4 sw=4 tw=0 et :
